### ISSUE TITLE
PreparedStatement is not supported

### ISSUE THREAD

**Issue by suryakiran-c** [forcedotcom/Salesforce-CDP-jdbc#162]
I'm trying to use preparedStatement as in example provided in Readme. 
```
        PreparedStatement preparedStatement = connection.prepareStatement("select FirstName__c, BirthDate__c, YearlyIncome__c from Individual__dlm where FirstName__c = ? and YearlyIncome__c > ?");
        preparedStatement.setString(0, "Angella");
        preparedStatement.setInt(1, 1000);
```

But I get this error, 
`Exception in thread "main" java.sql.SQLFeatureNotSupportedException: PreparedStatement is not supported
	at com.salesforce.cdp.queryservice.core.QueryServiceConnection.prepareStatement(QueryServiceConnection.java:147)
	at TestConnectivity.main(TestConnectivity.java:38)
`

https://github.com/forcedotcom/Salesforce-CDP-jdbc/blob/dea103d6afde802764659944e7f0932000e9f710/src/main/java/com/salesforce/cdp/queryservice/core/QueryServiceConnection.java#L146

Looks like prepareStatement is removed in new release [release_2024.4b.2](https://github.com/forcedotcom/Salesforce-CDP-jdbc/releases/tag/release_2024.4b.2)
But it was available till previous releases [release_2024.4a.1](https://github.com/forcedotcom/Salesforce-CDP-jdbc/releases/tag/release_2024.4a.1)

**Comment by suryakiran-c** [comment]
Never mind. It was published in [Release notes](https://github.com/forcedotcom/Salesforce-CDP-jdbc/releases/tag/release_2024.4b.2).
